/**
 * qtables.js — Real camera JPEG quantization tables, in zigzag order.
 *
 * The quantization table is one of the strongest camera fingerprints in a JPEG:
 * manufacturers use their own, forensic tools match against databases of them,
 * and the browser's table says "browser". Substituting the DQT bytes alone
 * would change the picture, because the coefficients were quantized against the
 * old table, so js/jpeg-requantize.js rescales the coefficients onto the new
 * table instead.
 *
 * These are measured, not invented. Each was read straight out of the DQT
 * segment of unmodified camera originals on Wikimedia Commons, and only tables
 * that came back byte-identical from two or more independent devices of the
 * same make are listed — one sample cannot tell a camera's table apart from
 * whatever re-encoded the upload. Values are in zigzag order, exactly as they
 * sit in the file; note that Pillow's `.quantization` returns them in natural
 * order instead, which is a good way to record the wrong numbers.
 *
 * A make that is absent simply keeps the browser's own table, which is what the
 * tool did for every image before this existed. Adding one is a data change:
 * read the DQT out of a genuine original and paste it in.
 *
 * Regenerated by scratchpad/dqt/gen_qtables.py.
 */

export const CAMERA_QTABLES = {
  // Pixel 6a 4032x3024, Pixel 7a 4624x3472, Pixel 8 Pro 4080x3072 (Wikimedia Commons originals)
  "Google": {
    luma: [
        3,   3,   4,   2,   5,   1,   1,   4,
        4,   1,   1,   4,   4,   4,   1,   3,
        4,   4,   4,   3,   3,   6,   6,   5,
        5,   5,   6,   7,   8,   8,   7,   7,
        7,   7,   7,   8,   7,   8,   9,   8,
        8,   9,  10,  10,   9,   9,  11,   9,
        7,   8,  11,  11,  11,  10,  12,  12,
       12,   9,  10,  12,  11,  11,  11,  10,
    ],
    chroma: [
        3,   3,   3,   5,   4,   5,   7,   6,
        6,   7,  11,   8,   8,   8,  11,  11,
       11,  11,  11,  11,  11,  11,  11,  11,
       11,  11,  11,  11,  12,  12,  11,  11,
       11,  11,  12,  12,  12,  12,  12,  11,
       11,  12,  12,  12,  12,  12,  12,  12,
       12,  12,  12,  12,  12,  12,  12,  12,
       12,  12,  12,  12,  12,  12,  12,  12,
    ],
  },
};

/** The table for a camera make, or null to leave the browser's own in place. */
export function qtableFor(make) {
  return CAMERA_QTABLES[make] || null;
}
